application: lifetrckr
version: 1
runtime: python
api_version: 1

handlers:

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /images
  static_dir: ui/images

- url: /css
  static_dir: ui/css

- url: /js
  static_dir: ui/js

- url: .*
  script: home.py

- url: /_ah/mail/.+
  script: incoming_mail.py
  login: admin

builtins:
- remote_api: on

inbound_services:
- mail
