application: lifetrckr
version: 1
runtime: python
api_version: 1

handlers:

- url: /favicon.ico
  static_files: images/favicon.ico 
  upload: images/favicon.ico

- url: /images
  static_dir: ui/images

- url: /css
  static_dir: ui/css

- url: /js
  static_dir: ui/js

- url: /fonts
  static_dir: ui/fonts

- url: /intern/css
  static_dir: intern/css

- url: /intern/js
  static_dir: intern/js

- url: .*
  script: bindings.py

- url: /_ah/mail/.+
  script: communications/incoming_mail.py
  login: admin

builtins:
- remote_api: on

inbound_services:
- mail
